Agent designer tutorial first draft
silverpond/highlighter-docs pull request #14
Opened 2023-10-03 07:23 UTC by rskew

2023-10-06 05:11 UTC, simon-dev-ml commented
Hey @rskew could you pls link the issue in the description?

2023-10-06 05:22 UTC, simon-dev-ml requested changes
Apart from that looks good, language and active voice is good

2023-10-06 05:22 UTC, simon-dev-ml commented on content/docs/tutorials/creating_and_editing_agents.md
> +Highlighter enables you identify high-level entities and attributes in low-level data. This work is delegated to "agents", which could be a human annotating images, video or text, or it could be a se
I guess "agents' should be capitalised to match other uses

2023-10-06 05:22 UTC, simon-dev-ml commented on content/docs/tutorials/creating_and_editing_agents.md
> +2. Give your new Process a name, ignore the rest of the form and click "Save Assessment Process".
could delete this
```suggestion
2. Give your new Process a name and click "Save Assessment Process".
```

2023-10-06 05:22 UTC, simon-dev-ml commented on content/docs/tutorials/creating_and_editing_agents.md
> +3. Navigate to the "Stage Definition" tab of your new Process and under "Machine Assessments" press "New Machine Assessment Stage".
```suggestion
3. Navigate to the "Stage Definition" tab of your new Process and under "Machine Assessments" click "New Machine Assessment Stage".
```

2023-10-06 05:22 UTC, simon-dev-ml commented on content/docs/tutorials/creating_and_editing_agents.md
> +You should now be looking at a blank agent. By default it has two nodes: Inputs and Outputs. You can drag these around.
Your screenshot has "Pipeline Outputs" so probably should use that, unless you've changed that to new terminology in which case screenshot needs updating

2023-10-06 05:22 UTC, simon-dev-ml commented on content/docs/tutorials/creating_and_editing_agents.md
> +To add a Capability to the Agent, click on "Add Capability" in the top right. You will see a list of Capabilities; select a "detector" Capability from the list. Clicking the detector will add it to t
Needs space between image and this paragraph

2023-10-06 05:22 UTC, simon-dev-ml commented on content/docs/tutorials/creating_and_editing_agents.md
> +You can add edges to the Outputs node by dragging the outputs of the detector and dropping the new edge on the Outputs node. These edges represent data returned by your Agent.
?
```suggestion
You can add edges to the Outputs node by dragging the outputs of the detector and dropping the new edge on the Outputs node. These edges represent data that your Agent will return.
```

2023-10-06 05:22 UTC, simon-dev-ml commented on content/docs/tutorials/creating_and_editing_agents.md
> +### Tidy Up
Not sure we even need this section? I assuming someone will want to keep their agent

2023-10-20 02:04 UTC, rskew commented on content/docs/tutorials/creating_and_editing_agents.md
> +### Tidy Up
Since this is a "tutorial" rather than a "how-to guide", the idea is someone runs through it to learn "how" to add an agent, rather than running through it when they just want an agent created. https://diataxis.fr/tutorials-how-to/

This might be more useful as a "how-to guide", in which case I would remove the setup section as well as the user should already have an Assessment Process by the time they reach for a guide to help them create an agent.

What do you reckon?

2023-10-20 02:05 UTC, rskew commented on content/docs/tutorials/creating_and_editing_agents.md
> +### Tidy Up
I've added a note about ignoring the section if the user wants to use their new Assessment Process and Agent

2023-10-20 02:08 UTC, rskew commented on content/docs/tutorials/creating_and_editing_agents.md
> +You should now be looking at a blank agent. By default it has two nodes: Inputs and Outputs. You can drag these around.
Good point. I'll have to remember to update this when I migrate "Pipeline Inputs" to "Inputs".

2023-10-20 02:08 UTC, rskew commented on content/docs/tutorials/creating_and_editing_agents.md
> +3. Navigate to the "Stage Definition" tab of your new Process and under "Machine Assessments" press "New Machine Assessment Stage".
done

2023-10-20 02:08 UTC, rskew commented on content/docs/tutorials/creating_and_editing_agents.md
> +Highlighter enables you identify high-level entities and attributes in low-level data. This work is delegated to "agents", which could be a human annotating images, video or text, or it could be a se
Done

2023-10-20 02:08 UTC, rskew commented on content/docs/tutorials/creating_and_editing_agents.md
> +2. Give your new Process a name, ignore the rest of the form and click "Save Assessment Process".
Done

2023-10-20 02:14 UTC, rskew commented on content/docs/tutorials/creating_and_editing_agents.md
> +To add a Capability to the Agent, click on "Add Capability" in the top right. You will see a list of Capabilities; select a "detector" Capability from the list. Clicking the detector will add it to t
Done

2023-10-20 02:15 UTC, rskew commented
@simon-dev-ml comments actioned

2023-10-23 01:44 UTC, simon-dev-ml commented on content/docs/tutorials/creating_and_editing_agents.md
> +### Tidy Up
Yeh I reckon this is actually more of a how-to guide than a tutorial anyway. There is a 'how-to- guides section on main now so you could just add it to that

2023-10-23 01:45 UTC, simon-dev-ml commented on content/docs/tutorials/creating_and_editing_agents.md
> +Ignore this section if you want to continue using your new Assessment Process an Agent.
```suggestion
Ignore this section if you want to continue using your new Assessment Process and Agent.
```

2023-10-23 01:49 UTC, simon-dev-ml commented
Cool, few more things and I think we're there

2023-10-23 05:56 UTC, rskew commented on content/docs/tutorials/creating_and_editing_agents.md
> +### Tidy Up
Ok I've made it a How-To Guide

2023-10-24 03:31 UTC, simon-dev-ml requested changes
Also you'll probably need to rebase on main to get my how-to article from there, to integrate it into your new section. Sorry review of this has been so piecemeal, what with a lot going on and me being away for 3 days...

2023-10-24 03:31 UTC, simon-dev-ml commented on content/docs/howtos/creating_and_editing_agents.md
> +To add a Capability to the Agent, click on "Add Capability" in the top right. You will see a list of Capabilities; select a "detector" Capability from the list. Clicking the detector will add it to t
Just had a thought - you might want to mention something here such as: "Different capabilities will be available depending on what has been previously created in your account. To create a new capability see your account administrator" or something similar. Because someone following this for the first time won't necessarily see any there.

2023-10-24 05:10 UTC, rskew commented on content/docs/howtos/creating_and_editing_agents.md
> +To add a Capability to the Agent, click on "Add Capability" in the top right. You will see a list of Capabilities; select a "detector" Capability from the list. Clicking the detector will add it to t
Good point, added

2023-10-24 05:10 UTC, rskew commented on content/docs/howtos/creating_and_editing_agents.md
> +To add a Capability to the Agent, click on "Add Capability" in the top right. You will see a list of Capabilities; select a "detector" Capability from the list. Clicking the detector will add it to t
also rebased

2023-10-24 06:30 UTC, simon-dev-ml approved these changes

2023-10-24 06:30 UTC, simon-dev-ml commented
Looks good man, merge away!

2023-10-24 07:39 UTC, merged