Upload local datasets using cli
silverpond/highlighter-docs pull request #15
Opened 2024-03-12 06:11 UTC by tall-josh

2024-03-13 00:11 UTC, simon-dev-ml requested changes

2024-03-13 00:11 UTC, simon-dev-ml commented on content/docs/how-to-guides/upload-data-using-cli.md
> +Upon completion you will also have a duplica coco json file with the `.images[].file_
```suggestion
Upon completion you will also have a duplicate coco json file with the `.images[].file_
```

2024-03-13 00:11 UTC, simon-dev-ml commented on content/docs/how-to-guides/upload-data-using-cli.md
> +This tutorial expects you:
```suggestion
This tutorial expects you have done the following:
```

2024-03-13 00:11 UTC, simon-dev-ml commented on content/docs/how-to-guides/upload-data-using-cli.md
> +  1. [Highlighter Credentials](./highlighter-credentials.md)
```suggestion
  1. Created [Highlighter Credentials](./highlighter-credentials.md)
```

2024-03-13 00:11 UTC, simon-dev-ml commented on content/docs/how-to-guides/upload-data-using-cli.md
> +  2. Create a Data Source in the Highlighter Web UI, note the ID from the URL, eg:
```suggestion
  2. Created a Data Source in the Highlighter Web UI, note the ID from the URL, eg:
```

2024-03-13 00:11 UTC, simon-dev-ml commented on content/docs/how-to-guides/upload-data-using-cli.md
> +  4. Create the Object Classes on the same name in Highlighter
```suggestion
  4. Created the Object Classes on the same name in Highlighter
```

2024-03-13 00:11 UTC, simon-dev-ml commented on content/docs/how-to-guides/upload-data-using-cli.md
> +  3. Create an Assessment Process in Highlighter, note the ID from the URL, eq:
```suggestion
  3. Created an Assessment Process in Highlighter, note the ID from the URL, eq:
```

2024-03-13 00:11 UTC, simon-dev-ml commented on content/docs/how-to-guides/upload-data-using-cli.md
> +  5. Add the Object Classes to the Assessment Process
```suggestion
  5. Added the Object Classes to the Assessment Process
```

2024-03-13 00:11 UTC, simon-dev-ml commented on content/docs/how-to-guides/upload-data-using-cli.md
> +  6. Your Highlighter User Id
```suggestion
  6. Found your Highlighter User Id
```

2024-03-13 22:43 UTC, rskew reviewed
Great work!

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/highlighter-credentials.md
> +profile_name:
```suggestion
compuglobalhypermeganet:
```

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/highlighter-credentials.md
> +You can now use the `--profile` option when using the CLI or
```suggestion
You can now use the `--profile compuglobalhypermeganet` option when using the CLI or
```

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +lead = "How to upload images and optionally annotations to Highlighter using the CLI"
I don't think this line adds much, the title and first paragraph sum it up pretty well I think:

![screenshot641](https://github.com/silverpond/highlighter-docs/assets/16100155/bc4d2b04-1a41-473a-9579-b491677a566e)

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +  1. Have [Highlighter Credentials →](../highlighter-credentials/)
```suggestion
  1. Created [Highlighter Credentials →](../highlighter-credentials/)
```

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +  `https://compuglobalhypermeganet.highlighter.ai/data_source/DATASOURCE_ID`
```suggestion
  `https://your-account-subdomain.highlighter.ai/data_source/DATASOURCE_ID`
```
Non-blocking. Nothing against `compuglobalhypermeganet` but it takes the focus away from the `DATASOURCE_ID` when reading

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +  2. Created a Data Source in the Highlighter Web UI, note the ID from the URL, eg:
```suggestion
  2. Created a Data Source in the Highlighter Web UI, note the Data Source ID from the URL, eg:
```

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +
```suggestion
```
Non-blocking suggestion. I don't think this line is needed

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +lead = "How to upload images and optionally annotations to Highlighter using the CLI"
```suggestion
```

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +newly created Highlighter file ids to the original files you uploaded.
Where is this new local directory with symlinks?

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +### Upload Images From a Text File
```suggestion
### Upload Images Listed in a Text File
```

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +# Upload images with paths in file
```suggestion
```shell
# Upload images with paths in file
```

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +### From a Coco json file
```suggestion
### Upload a Dataset from a Coco JSON File
```

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +If needed you can use `--image-dir` to append an directory to the `file_name`s
```suggestion
If needed you can use `--image-dir` to append a directory to the `file_name`s
```

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +name` values updated to use the newly create Highlighter file ids
```suggestion
Upon completion you will also have a duplicate coco json file with the `.images[].file_name` values updated to use the newly create Highlighter file ids
```
line break creates a space

![screenshot642](https://github.com/silverpond/highlighter-docs/assets/16100155/7a80e88b-49d8-4fd6-8801-c6cbcc4011f1)

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +# Upload images with paths image_dir/PATH
```suggestion
# Upload images located at foo/image_dir/FILENAME with paths image_dir/FILENAME listed in coco.json
```

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +**Coco Bounding Box or Polygon segmentaton are the only formats supported from the CLI at the moment**
```suggestion
**Note: Coco Bounding Box or Polygon segmentaton are the only formats supported from the CLI at the moment**
```

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +  1. Have [Highlighter Credentials](./highlighter-credentials.md)
```suggestion
  1. Created [Highlighter Credentials](./highlighter-credentials.md)
```

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +  `https://compuglobalhypermeganet.highlighter.ai/data_source/DATASOURCE_ID`
```suggestion
  `https://your-account-subdomain.highlighter.ai/data_source/DATASOURCE_ID`
```
as above

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +  `https://compuglobalhypermeganet.highlighter.ai/projects/PROCESS_ID`
```suggestion
  `https://your-account-subdomain.highlighter.ai/projects/PROCESS_ID`
```
as above

2024-03-13 22:43 UTC, rskew commented on content/docs/how-to-guides/upload-data-using-cli.md
> +# Upload the images, after this you should have a duplicate of train.json
```suggestion
# Upload the images. After this you should have a duplicate of train.json
```

2024-03-14 03:41 UTC, simon-dev-ml commented on content/docs/how-to-guides/upload-data-using-cli.md
> +# Upload the labels in the dataset to an Assessment Process
Need to add docs before this line to create the object classes and add them to the process

2024-03-15 01:16 UTC, simon-dev-ml commented on content/docs/how-to-guides/upload-data-using-cli.md
> +# Upload the labels in the dataset to an Assessment Process
@tall-josh Let me know once you've done this and I can re-review

2024-03-19 00:02 UTC, simon-dev-ml requested changes
Just few more little things and my comment [here](https://github.com/silverpond/highlighter-docs/pull/15#discussion_r1524162416), apart from that looking good

2024-03-19 00:02 UTC, simon-dev-ml commented on content/docs/how-to-guides/upload-data-using-cli.md
> +## Images And Observations
```suggestion
## Upload Images And Observations
```

2024-03-25 02:57 UTC, simon-dev-ml approved these changes

2024-03-25 02:58 UTC, merged